/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET DAML SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.digitalasset.ledger.client.{binding=>$u0020lfdomainapi}
import _root_.com.digitalasset.ledger.api.v1.{value=>$u0020rpcvalue}
package com.knoldus {
  package Main {
    final case class RequestShare(requestQuantity: ` lfdomainapi`.Primitive.Int64) extends ` lfdomainapi`.ValueRef

    object RequestShare extends ` lfdomainapi`.ValueRefCompanion with _root_.scala.Function1[` lfdomainapi`.Primitive.Int64, _root_.com.knoldus.Main.RequestShare] {
      import _root_.scala.language.higherKinds;
      trait view[` C`[_]] extends ` lfdomainapi`.encoding.RecordView[` C`, view] { $u0020view =>
        val requestQuantity: ` C`[` lfdomainapi`.Primitive.Int64];
        final override def hoist[` D`[_]](` f` : _root_.scalaz.~>[` C`, ` D`]): view[` D`] = {
          final class $anon extends _root_.scala.AnyRef with view[` D`] {
            override val requestQuantity = ` f`(` view`.requestQuantity)
          };
          new $anon()
        }
      };
      implicit val `RequestShare Value`: ` lfdomainapi`.Value[_root_.com.knoldus.Main.RequestShare] = {
        final class $anon extends this.`Value ValueRef`[_root_.com.knoldus.Main.RequestShare] {
          override def write(value: _root_.com.knoldus.Main.RequestShare): ` rpcvalue`.Value.Sum = ` record`(scala.Tuple2("requestQuantity", ` lfdomainapi`.Value.encode(value.requestQuantity)));
          override def read(argValue: ` rpcvalue`.Value.Sum): _root_.scala.Option[_root_.com.knoldus.Main.RequestShare] = argValue.record.flatMap(((` r` ) => if (` r`.fields.length.==(1))
            ` r`.fields(0) match {
              case ` rpcvalue`.RecordField((""| "requestQuantity"), _root_.scala.Some(zv0)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Int64](zv0) match {
                case _root_.scala.Some(requestQuantity) => Some(RequestShare(requestQuantity))
                case _root_.scala.None => _root_.scala.None
              })
              case _ => _root_.scala.None
            }
          else
            _root_.scala.None))
        };
        new $anon()
      };
      override protected val ` dataTypeId` = ` mkDataTypeId`(`Package IDs`.Main, "Main", "RequestShare");
      implicit def `RequestShare LfEncodable`: ` lfdomainapi`.encoding.LfEncodable[_root_.com.knoldus.Main.RequestShare] = {
        final class $anon extends ` lfdomainapi`.encoding.LfEncodable[_root_.com.knoldus.Main.RequestShare] {
          override def encoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding): lte.Out[_root_.com.knoldus.Main.RequestShare] = {
            object `view ` extends view[lte.Field] {
              val requestQuantity = lte.field("requestQuantity", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Int64](lte))
            };
            {
              val `recordFields `: lte.RecordFields[_root_.com.knoldus.Main.RequestShare] = lte.RecordFields.xmapN(lte.fields(`view `.requestQuantity))({
                case requestQuantity => _root_.com.knoldus.Main.RequestShare(requestQuantity)
              })({
                case _root_.com.knoldus.Main.RequestShare(requestQuantity) => requestQuantity
              });
              lte.record(` dataTypeId`, `recordFields `)
            }
          }
        };
        new $anon()
      }
    }
  }
}
