/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET DAML SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
package com.knoldus {
  private object `Package IDs` {
    val `DA.Date.Types`: _root_.scala.Predef.String = "bfcd37bd6b84768e86e432f5f6c33e25d9e7724a9d42e33875ff74f6348e733f";
    val `DA.Generics`: _root_.scala.Predef.String = "75c0432002539aa2b4dfad33a29023a21211dde15b0d1deafbd4a1a3fe7cdd01";
    val `DA.Internal.Down`: _root_.scala.Predef.String = "057eed1fd48c238491b8ea06b9b5bf85a5d4c9275dd3f6183e0e6b01730cc2ba";
    val `DA.Internal.Template`: _root_.scala.Predef.String = "d14e08374fc7197d6a0de468c968ae8ba3aadbf9315476fd39071831f5923662";
    val `DA.Logic.Types`: _root_.scala.Predef.String = "c1f1f00558799eec139fb4f4c76f95fb52fa1837a5dd29600baa1c8ed1bdccfd";
    val `DA.Monoid.Types`: _root_.scala.Predef.String = "6c2c0667393c5f92f1885163068cd31800d2264eb088eb6fc740e11241b2bf06";
    val `DA.Next.Map`: _root_.scala.Predef.String = "75c0432002539aa2b4dfad33a29023a21211dde15b0d1deafbd4a1a3fe7cdd01";
    val `DA.Next.Set`: _root_.scala.Predef.String = "75c0432002539aa2b4dfad33a29023a21211dde15b0d1deafbd4a1a3fe7cdd01";
    val `DA.NonEmpty.Types`: _root_.scala.Predef.String = "e22bce619ae24ca3b8e6519281cb5a33b64b3190cc763248b4c3f9ad5087a92c";
    val `DA.Random`: _root_.scala.Predef.String = "75c0432002539aa2b4dfad33a29023a21211dde15b0d1deafbd4a1a3fe7cdd01";
    val `DA.Semigroup.Types`: _root_.scala.Predef.String = "8a7806365bbd98d88b4c13832ebfa305f6abaeaf32cfa2b7dd25c4fa489b79fb";
    val `DA.Time.Types`: _root_.scala.Predef.String = "733e38d36a2759688a4b2c4cec69d48e7b55ecc8dedc8067b815926c917a182a";
    val `DA.Types`: _root_.scala.Predef.String = "40f452260bef3f29dede136108fc08a88d5a5250310281067087da6f0baddff7";
    val `DA.Validation.Types`: _root_.scala.Predef.String = "99a2705ed38c1c26cbb8fe7acf36bbf626668e167a33335de932599219e0a235";
    val `GHC.Tuple`: _root_.scala.Predef.String = "6839a6d3d430c569b2425e9391717b44ca324b88ba621d597778811b2d05031d";
    val `GHC.Types`: _root_.scala.Predef.String = "518032f41fd0175461b35ae0c9691e08b4aea55e62915f8360af2cc7a1f2ba6c";
    val Main: _root_.scala.Predef.String = "64803a3087ae6c06ffd08f1c8a3828f583e3aea2b22f83411a435581545bcf29"
  }
}
